########################
# Display Entity Utils #
#      By DonnyPZ      #
########################

localStorageEnabled: true

#The database and collections will automatically be created if it does not exist already
mongodb:
  enabled: false
  connectionString: ""
  database: "DisplayEntityUtils"
  groupCollection: "saved_displays"
  animationCollection: "saved_animations"

mysql:
  enabled: false
  host: "localhost"
  port: 3306
  database: "mydb"
  username: "root"
  password: "password"
  useSSL: false
#Using connection url will override settings above
  connectionURL: ""

#Determine whether plugin commands should be registered and usable
#Plugin commands can only be re-enabled after a server restart
registerCommands: true

#Determine whether a group can be selected by more than one player at a time
#Leave this value as true to avoid conflicts when using "/mdis group selectnearest"
limitGroupSelections: true

#When selecting a group, this is the block that will be shown, marking an interaction's entity location
interactionPreviewBlock: TARGET

#Automatically select groups when using the command "/mdis group spawn"
autoSelectGroups: false

#The default persistence value that should be applied when spawning a group
defaultPersistence: true

#Attempts to automatically detect Spawned Display Entity Groups on Server Start
#Also attempts to asynchronously detect groups when a chunk loads
#This feature may not work 100% work on worlds that keep spawn in memory, but will work after a world reload (unload -> load)
automaticGroupDetection:
  enabled: true

  #Override the persistence value of detected groups
  #This is only really useful when existing groups/models are present, in abundance
  persistenceOverride:
    #Whether to override the persistence value of detected groups
    enabled: false

    #The overriding persistence value to set for a detected group
    persistent: true

    #Whether groups, when spawned, should automatically apply the "persistent" value, overriding its existing persistence
    #Manually toggle overriding for a group with "/mdis group togglepersistoverride"
    overrideByDefault: false

  #Maximum Search range for Interaction Entities in a Group
  #High values with frequent searches may lead to lag spikes and/or undesired results
  #Setting this value to 0 will effectively disable this feature
  maximumInteractionSearchRange: 7

  #Re-search previously searched chunks for Spawned Display Entity Groups
  #May cause lag when if many chunks are constantly being loaded and unloaded
  #May cause lag in chunks with many entities
  readSameChunks: false

  #Unregisters all groups in unloaded worlds
  #
  #Keep this enabled unless another plugin requires this setting to be disabled, or
  #if problems arise with this setting while using the API
  unregisterOnUnload:
    enabled: true
    worlds:
      - world
      - lobby

  #If true, groups in the listed worlds will not be unregistered
  #If false, groups in the listed worlds will be unregistered
    blacklist: true


#Automatically Pivot Interaction Entity when a DisplayEntityGroup is spawned
#in order to match the group's yaw
autoPivotInteractionsOnSpawn: true

#Enable this to allow overwriting of existing saved DisplayEntityGroups and Animations
overwriteExistingSaves: true


#This setting attempts to automatically cull Spawned Display Entity Groups based on the following options:
#
#    NONE: No Display Entities will be culled (Default Vanilla Option)
#    LOCAL: Display Entities will be culled individually based on their transformation's scale
#    LARGEST: All Display Entities within a group will have the same culling size as the largest culled entity in the group
#
#Use this setting at your own risk and ONLY if you know what you are doing.
#This may have client performance benefits for players when selecting the correct option for your server.
#LARGEST is the safest option to reduce Display Entities being culled too early, but may not bring any performance improvements
#
#That does not mean you SHOULD pick LARGEST, testing with LOCAL should be done first and if that brings about issue, adjusting culling adders should
#be done next, then trying LARGEST if issues still persist
# !KEEP IN MIND! it is NOT possible for the culling to be 100% perfect.
autoCulling: NONE

#The two settings below will add X amount of blocks to the culling range of all SpawnedDisplayEntityGroups
#If a group's culling width/height is 0 on the width and height, the group's culling width/height will become whatever value you set below
#Essentially, the value set below will be added to the group's culling width/height determined from "autoCulling"
#
#These settings will do nothing if "autoCulling" is set to NONE
#ONLY CHANGE THESE SETTINGS IF YOU KNOW WHAT YOU ARE DOING
widthCullingAdder: 1.5
heightCullingAdder: 1.5

#Optionally cache animations after retrieving them from a storage location.
#This option prevents constant server freezes/lag when retrieving animations at the cost of using more memory
cacheAnimations:
  enabled: true

  #How long an animation must be unused before it's uncached
  #-1 to disable expiration
  expireTimeInSeconds: 900

#Attempt to improve server performance by playing animations asynchronously
#Keep this value as false if animations do not display as intended or are choppy
asynchronousAnimations: false




