name: DisplayEntityUtils
version: '${project.version}'
main: net.donnypz.displayentityutils.DisplayEntityPlugin
author: DonnyPZ
load: POSTWORLD
api-version: 1.20
softdepend:
  - MythicMobs
  - LibsDisguises
  - Skript
  - ViaVersion
depend:
  - packetevents
commands:
  managedisplays:
    aliases: [mdis]
    description:
    usage:
